    spring.application.name=project
    spring.datasource.url=${DB_URL}
    spring.datasource.username=${DB_USER}
    spring.datasource.password=${DB_PASSWORD}
    hibp.base-url=${URL_BASE_FIND_BY_EMAIL_HIBP}
    hibp.api-key=${HIBP_API_KEY}
    spring.jpa.show_sql=true
