    spring.application.name=project
    spring.datasource.url=${DB_URL}
    spring.datasource.username=${DB_USER}
    spring.datasource.password=${DB_PASSWORD}

    audit.datasource.url=${DB_AUDIT_URL}
    audit.datasource.username=${DB_USER}
    audit.datasource.password=${DB_PASSWORD}
    spring.jpa.hibernate.ddl-auto=update

    hibp.base-url=${URL_BASE_FIND_BY_EMAIL_HIBP}
    hibp.api-key=${HIBP_API_KEY}
    spring.jpa.show_sql=true

    spring.mvc.pathmatch.use-suffix-pattern=true

