pipeline {
    agent any

    tools {
        maven "M3"
    }

    environment {
        APP_NAME = "api-search"
        VERSION = "1.0.${BUILD_NUMBER}"

        DB_URL = credentials('DB_URL')
        DB_USER = credentials('DB_USER')
        DB_PASSWORD = credentials('DB_PASSWORD')
        DB_AUDIT_URL = credentials('DB_AUDIT_URL')

        URL_BASE_FIND_BY_EMAIL_HIBP = credentials('URL_BASE_FIND_BY_EMAIL_HIBP')
        HIBP_API_KEY = credentials('HIBP_API_KEY')

        SERVER = "luan@100.73.69.118"
        STAGING_PATH = "/opt/api/spring-staging"
        PRODUCTION_PATH = "/opt/api/spring-production"
    }

    stages {

        stage('Checkout'){
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh "mvn clean package -DskipTests"
            }
        }

        stage('Test'){
    steps{
        withCredentials([
            string(credentialsId: 'DB_URL', variable: 'DB_URL'),
            string(credentialsId: 'DB_USER', variable: 'DB_USER'),
            string(credentialsId: 'DB_PASSWORD', variable: 'DB_PASSWORD'),
            string(credentialsId: 'URL_BASE_FIND_BY_EMAIL_HIBP', variable: 'URL_BASE_FIND_BY_EMAIL_HIBP'),
            string(credentialsId: 'HIBP_API_KEY', variable: 'HIBP_API_KEY'),
            string(credentialsId: 'DB_AUDIT_URL', variable: 'DB_AUDIT_URL')
        ]) {
            sh '''
            mvn test \
            -Dspring.datasource.url=$DB_URL \
            -Dspring.datasource.username=$DB_USER \
            -Dspring.datasource.password=$DB_PASSWORD \
            -Dhibp.base-url=$URL_BASE_FIND_BY_EMAIL_HIBP \
            -Dhibp.api-key=$HIBP_API_KEY \
            -Daudit.datasource.url=$DB_AUDIT_URL
            '''
            }
        }
    }

        stage('Package Version'){
            steps {
                sh "mv target/*.jar target/${APP_NAME}-${VERSION}.jar"
            }
        }

        stage('Deploy Staging'){
            when {
                expression {
                    env.GIT_BRANCH == 'origin/staging'
                }
            }
            steps {
                sshagent(['vps-ssh']) {
                    sh """
                        scp target/${APP_NAME}-${VERSION}.jar ${SERVER}:${STAGING_PATH}/app.jar

                        ssh ${SERVER} '
                            systemctl restart api-search-staging
                        '
                    """
                }
            }
        }

        stage('Deploy Production'){
            when {
                expression {
                    env.GIT_BRANCH == 'origin/main'
                }
            }
            steps {
                sshagent(['vps-ssh']) {
                    sh """
                        scp target/${APP_NAME}-${VERSION}.jar ${SERVER}:${PROD_PATH}/app.jar

                        ssh ${SERVER} '
                            systemctl restart api-search
                        '
                    """
                }
            }
        }
    }

    post {
        success {
            emailext(
                subject: "🚀 Done Pipeline - ${JOB_NAME} #${BUILD_NUMBER}",
                body: """
                🚀 Done Pipeline!

                🧪 Build: SUCCESS
                🚀 Deploy: SUCCESS
                🚨 Notify: SENT

                📦 Project: ${JOB_NAME}
                🌿 Branch: [${env.GIT_BRANCH}]
                👤 ILSolutions

                🔢 Build Number: ${BUILD_NUMBER}
                🖥️ Jenkins: ${JENKINS_URL}

                🔗 Build URL:
                ${BUILD_URL}

                """,
                to: "igor.luan.solutions@gmail.com"
            )
        }

        failure {
            emailext(
                subject: "❌ Failed Pipeline ! - ${JOB_NAME} #${BUILD_NUMBER}",
                body: """
                ❌ Failed Pipeline!

                📦 Project: ${JOB_NAME}
                🌿 Branch: [${env.GIT_BRANCH}]

                🔢 Build Number: ${BUILD_NUMBER}

                🔗 Check:
                ${BUILD_URL}
                """,
                to: "igor.luan.solutions@gmail.com"
            )
        }

        always {
            junit '**/target/surefire-reports/TEST-*.xml'
            archiveArtifacts 'target/*.jar'
        }
    }
}