pipeline {
    agent any

    tools {
        maven "M3"
    }

    environment {
        APP_NAME = "api-search"
        VERSION = "1.0.${BUILD_NUMBER}"

        DB_URL = credentials('DB_URL')
        DB_USER = credentials('DB_USER')
        DB_PASS = credentials('USER_PASSWORD')
    }

    stages {

        stage('Checkout'){
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh "mvn clean package -DskipTests"
            }
        }

        stage('Test'){
    steps{
        withCredentials([
            string(credentialsId: 'DB_URL', variable: 'DB_URL'),
            string(credentialsId: 'DB_USER', variable: 'DB_USER'),
            string(credentialsId: 'USER_PASSWORD', variable: 'DB_PASS')
        ]) {
            sh '''
            mvn test \
            -Dspring.datasource.url=$DB_URL \
            -Dspring.datasource.username=$DB_USER \
            -Dspring.datasource.password=$DB_PASS
            '''
        }
    }
}

        stage('Package Version'){
            steps {
                sh "mv target/*.jar target/${APP_NAME}-${VERSION}.jar"
            }
        }

        stage('Deploy Staging'){
            when {
                expression {
                    env.GIT_BRANCH == 'origin/staging'
                }
            }
            steps {
                sh """
                echo "Deploy in staging"
                mkdir -p staging
                cp target/${APP_NAME}-${VERSION}.jar staging/
                """
            }
        }

        stage('Deploy Production'){
            when {
                expression {
                    env.GIT_BRANCH == 'origin/main'
                }
            }
            steps {
                sh """
                echo "Deploy in production"
                mkdir -p prod
                cp target/${APP_NAME}-${VERSION}.jar prod/
                """
            }
        }
    }

    post {
        success {
            emailext(
                subject: "🚀 Done Pipeline - ${JOB_NAME} #${BUILD_NUMBER}",
                body: """
                🚀 Done Pipeline!

                🧪 Build: SUCCESS
                🚀 Deploy: SUCCESS
                🚨 Notify: SENT

                📦 Project: ${JOB_NAME}
                🌿 Branch: [${env.GIT_BRANCH}]
                👤 ILSolutions

                🔢 Build Number: ${BUILD_NUMBER}
                🖥️ Jenkins: ${JENKINS_URL}

                🔗 Build URL:
                ${BUILD_URL}
                """,
                to: "igor.luan.solutions@gmail.com"
            )
        }

        failure {
            emailext(
                subject: "❌ Failed Pipeline! - ${JOB_NAME} #${BUILD_NUMBER}",
                body: """
                ❌ Failed Pipeline !

                📦 Project: ${JOB_NAME}
                🌿 Branch: [${env.GIT_BRANCH}]

                🔢 Build Number: ${BUILD_NUMBER}

                🔗 Check:
                ${BUILD_URL}
                """,
                to: "igor.luan.solutions@gmail.com"
            )
        }

        always {
            junit '**/target/surefire-reports/TEST-*.xml'
            archiveArtifacts 'target/*.jar'
        }
    }
}